# Generated by Django 3.1.7 on 2021-03-13 07:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225)),
                ('job', models.CharField(max_length=225)),
                ('address', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='trinerdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trainer_name', models.CharField(max_length=255)),
                ('Course', models.CharField(max_length=255)),
                ('Student_Name', models.CharField(max_length=255)),
                ('Duration', models.CharField(max_length=255)),
                ('Timeslate', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='userdetai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('passwordc', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('role', models.CharField(max_length=255)),
            ],
        ),
    ]
